/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    NutAvatar: typeof import('@nutui/nutui-taro')['Avatar']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCalendar: typeof import('@nutui/nutui-taro')['Calendar']
    NutCategory: typeof import('@nutui/nutui-taro')['Category']
    NutCategoryPane: typeof import('@nutui/nutui-taro')['CategoryPane']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutDatePicker: typeof import('@nutui/nutui-taro')['DatePicker']
    NutDialog: typeof import('@nutui/nutui-taro')['Dialog']
    NutImage: typeof import('@nutui/nutui-taro')['Image']
    NutMenu: typeof import('@nutui/nutui-taro')['Menu']
    NutMenuItem: typeof import('@nutui/nutui-taro')['MenuItem']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutPrice: typeof import('@nutui/nutui-taro')['Price']
    NutSideNavbar: typeof import('@nutui/nutui-taro')['SideNavbar']
    NutSideNavbarItem: typeof import('@nutui/nutui-taro')['SideNavbarItem']
    NutSubSideNavbar: typeof import('@nutui/nutui-taro')['SubSideNavbar']
    NutSwiper: typeof import('@nutui/nutui-taro')['Swiper']
    NutSwiperItem: typeof import('@nutui/nutui-taro')['SwiperItem']
  }
}
